The earlier exception handler we created, was local to the one Rest Controller in which it was defined.
![image](https://github.com/user-attachments/assets/19649459-780e-44fa-a65b-de0f04df36cf)
![image](https://github.com/user-attachments/assets/7b2d71fe-aecf-4036-9deb-972d6ad224be)
![image](https://github.com/user-attachments/assets/80de56f4-d2d2-4b5b-b4e5-c6ee470e430a)
![image](https://github.com/user-attachments/assets/706d9e70-6c9d-40bc-a41b-a0c4f20be380)
![image](https://github.com/user-attachments/assets/7064682a-24d7-4ab8-b781-007af2e8502a)
![image](https://github.com/user-attachments/assets/53ffe212-1162-4b25-9865-c2f67ef64335)
![image](https://github.com/user-attachments/assets/600e310d-196c-41d4-af81-2ab78e6b6f8a)

